### DISCUSSION TITLE
I refactored `src/login/Template.tsx` page but no change in the registeration page

### DISCUSSION THREAD

**Discussion by kasir-barati** [keycloakify/keycloakify#292] [Q&A] [answered]
Hi

I just happened to be in love with MUI and refactored the keycloakify to MUI, For the Login form it works like honey. No problem there. But the amazing thing is that register form even though is using same `Template.tsx` has no style.
# Register form
![image](https://user-images.githubusercontent.com/73785723/229212140-389320c4-f940-4ede-9ec9-0ea13314070e.png)
# Login form
![image](https://user-images.githubusercontent.com/73785723/229212258-de19633f-ddd7-4634-a0d5-7f25f8ff0adc.png)
And here is my conf for the realm and created client:
![image](https://user-images.githubusercontent.com/73785723/229212543-aba767a8-e687-4a84-92d9-f87656d34002.png)
![image](https://user-images.githubusercontent.com/73785723/229212621-245ed12f-3375-4932-a1f4-acfe0bc50464.png)
![image](https://user-images.githubusercontent.com/73785723/229212880-cfadca6c-6ba2-4bb8-b63d-279a35768fb4.png)

Any idea?

The worth thing is that in the registration page when I press f12 and look at the HTML I can see used ID's like `kc-header` which is used soly inside the `Template.tsx` in the project.

Here is the https://github.com/kasir-barati/customized-keycloakify-starter repo and you can run it easily by following `README.md` instructions. Thanks a lot for helping me. And thanks for this wonderful library :heart:

**Comment by kasir-barati** [comment]
New Discovery. I added a `console.log` inside my `src/login/Template.tsx` and realized that in login page I can see the log inside dev tools but in registration page I cannot see any log. Even I cannot see the log from the `src/login/RegisterUserProfile.tsx` file. So I guess kyecloak is not using this template for the registration page.

I do not know how to tell keycloak to use my custom generated ftl file from `src/login/RegisterUserProfile.tsx` instead of it own. any idea what's happening here?

**You can see where I add `console.log` in this commit: https://github.com/kasir-barati/customized-keycloakify-starter/commit/b03d87f625a7123e037e25a1a2029913ac92ec64**

**Comment by garronej** [comment]
can't run it now but usually this happens when you didn't build the theme at least once before running yarn start.  

First run `yarn build-keycloak-them` then `yarn start`

**Comment by kasir-barati** [comment, marked as answer]
Another thing, I forgot to follow this step and now I am trying to achieve it but it seems that `User Profile Enabled` is not where it is described here:

> NOTE: User profile is only available in Keycloak 15 and it's a beta feature that [needs to be enabled when launching keycloak](https://github.com/InseeFrLab/keycloakify/blob/59f106bf9e210b63b190826da2bf5f75fc8b7644/src/bin/build-keycloak-theme/build-keycloak-theme.ts#L116-L117) and [enabled in the console](https://user-images.githubusercontent.com/6702424/136874428-b071d614-c7f7-440d-9b2e-670faadc0871.png).

But no luck. I tried to active it in `docker-compose.yml` file with passing `KEYCLOAK_EXTRA_ARGS: -Dkeycloak.profile=preview` as env or `KEYCLOAK_EXTRA_ARGS: -Dkeycloak.profile.feature.scripts=enabled` or `JAVA_OPTS: -Dkeycloak.profile=preview` and then going to the GUI but there was not the following part in my GUI

![image](https://user-images.githubusercontent.com/73785723/229254640-39e9050e-99e3-4f58-b539-8c50404a7758.png)

Maybe I am misconfiguring my keycloak or the button is moved to somewhere else

**Reply by kasir-barati** [reply]
Since I was using the newest keycloak version I had to pass `KEYCLOAK_EXTRA_ARGS: --features=declarative-user-profile` as env to the container, here is my compose file and now I can see the `User Profile Enabled` button in my keycloak console:

```yml
version: "3"

services:
  postgres:
    image: bitnami/postgresql:15.2.0-debian-11-r13
    restart: always
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    volumes:
      - keycloak_db_volume:/bitnami/postgresql

  keycloak:
    image: bitnami/keycloak:20.0.5-debian-11-r8
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
      # - 8443:8443 HTTPS port
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: ${POSTGRESQL_DATABASE}
      KEYCLOAK_DATABASE_USER: ${POSTGRESQL_USERNAME}
      KEYCLOAK_DATABASE_PASSWORD: ${POSTGRESQL_PASSWORD}
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_ENABLE_STATISTICS: true
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_EXTRA_ARGS: --features=declarative-user-profile
      # And the following are for WildFly distribution:
      # Or IDK -Dkeycloak.profile.feature.declarative_user_profile=enabled
      # KEYCLOAK_EXTRA_ARGS: -Dkeycloak.profile=preview
      # KEYCLOAK_EXTRA_ARGS: -Dkeycloak.profile.feature.scripts=enabled
      # JAVA_OPTS: -Dkeycloak.profile=preview
      # KEYCLOAK_PRODUCTION: true In prod env and configure TLS pls
    volumes:
      - keycloak_volume:/tmp
      - ./build_keycloak/src/main/resources/theme/customized-keycloakify-starter:/opt/bitnami/keycloak/themes/customized-keycloakify-starter:rw

volumes:
  keycloak_volume:
  keycloak_db_volume:
```

TBH I did not try old versions, So it is up to you dear reader to test which value or key works.

BTW @garronej I suggest to update README.md or documentation for the newcomers :smile: 

**I did not test that what will happens to my registration page after activating this feature. So this is just for clarification and jotting what I am doing ATM**
