### DISCUSSION TITLE
Why were Docker files deleted?

### DISCUSSION THREAD

**Discussion by johnmanko** [keycloakify/keycloakify#579] [Q&A]
I just pull the latest changes (I think I was on v9.? cloned in Dec 2023), and I noticed the following conflicts:

```
	deleted by us:   .dockerignore
	deleted by us:   Dockerfile
	deleted by us:   src/keycloak-theme/account/KcApp.css
	deleted by us:   src/keycloak-theme/login/KcApp.css
	both modified:   vite.config.ts
```

The Docker files have been removed.  What's the reasoning behind that?

Also, since the *.css have been removed, I guess the method of changing the theme has changed.

**Comment by garronej** [comment]
Hello @johnmanko,  

V10 is still in release candidate and I haven't wrote the migration guide from v9 to v10 yet but I'm working on it.  
It'll be here: https://docs.keycloakify.dev/faq-and-help/migration-guides/v9-greater-than-v10  

The method of styling hasn't changed. It's just that the starter template is now actually a starter template.  
It no longer includes customization examples.  
Instead the documentation now includes detailed examples and tutorials on how to customize the base theme:  
Some examples:  
https://docs.keycloakify.dev/importing-assets/in-styles/plain-css
https://docs.keycloakify.dev/importing-assets/in-react-components  
https://docs.keycloakify.dev/theme-variants  

I removed the Dockerfile because the starter template is now strictly a Keycloak theme.  
If you want to integrate keycloakify in your project there is now a guide for that:  
https://docs.keycloakify.dev/keycloakify-in-my-codebase/in-your-react-project/in-your-vite-project  

If you don't feel like putting the pieces together and migrate your theme you can wait for the official release of Keycloakify v10.   
Otherwise I'm happy to answer any specific question you might have on our discord server: https://discord.gg/mJdYJSdcm4

**Reply by johnmanko** [reply]
That's cool.  I don't really need the migration guide since what I did was very minimal.  I'm going to scrap what I did and start over using the guides.  I'll probably keep the Dockerfile, though. :)

**Reply by garronej** [reply]
Cool!  
But what are you using the Dockerfile for exactly?

**Reply by garronej** [reply]
Because having a Dockerfile in the keycloakify-starter project was clearly out of scope for Keycloakify.  
If was just to show that you could have and App and a Keycloak theme as two deliverable of the same codebase.  
However I think that the majority of pepole either have their keycloak theme as a separate project or as a subproject of their monorepo: https://docs.keycloakify.dev/keycloakify-in-my-codebase/as-a-subproject-of-your-monorepo

**Reply by johnmanko** [reply]
I use the Docker image to initialize Keycloak theming through an init container in Kubernetes.  Basically, launch the theme container, writing the theme to a volume that's readily available to Keycloak themes folder upon startup, and then launch Keycloak.  It's a nice clean way to do it.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-keycloak-deploy
  namespace: my-app
  labels:
    helm.sh/chart: my-app-0.1.0
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: my-app-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      helm.sh/chart: my-app-0.1.0
      app.kubernetes.io/name: my-app
      app.kubernetes.io/instance: my-app
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/component: my-app-auth
  template:
    metadata:
      labels:
        helm.sh/chart: my-app-0.1.0
        app.kubernetes.io/name: my-app
        app.kubernetes.io/instance: my-app
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: my-app-auth
    spec:
      initContainers:
        - name: keycloak-theme
          image: my-app-keycloak-theme:0.0.1
          volumeMounts:
            - mountPath: /opt/app/volume
              name: theme-volume
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.4
          args: ["start-dev"]
          envFrom:
            - secretRef:
                name: my-app-keycloak-secret
            - configMapRef:
                name: my-app-keycloak-config
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          volumeMounts:
            - mountPath: /opt/keycloak/themes
              name: theme-volume
      volumes:
        - name: theme-volume
          emptyDir:
            sizeLimit: 50Mi
```

Dockerfile:
```
FROM node:18 as keycloakify_jar_builder
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get install -y maven;
COPY ./package.json ./yarn.lock /opt/app/
WORKDIR /opt/app
RUN yarn install --frozen-lockfile
COPY ./ /opt/app/
RUN yarn build-keycloak-theme

FROM busybox
WORKDIR /opt/app
COPY --from=keycloakify_jar_builder /opt/app/dist_keycloak/target/classes/theme/my-app /opt/app/my-app/
ENTRYPOINT [ "mv", "-n", "/opt/app/my-app", "/opt/app/volume/my-app" ]
```
