### ISSUE TITLE
How to deploy to a Maven repository the jar file

### ISSUE THREAD

**Issue by archimod95** [keycloakify/keycloakify#623]
Hi I was trying to publish to a remote repository the .jar file to be downloaded later into the Keycloak repository on my CI-CD, Any suggesstion, beacuse each time I try to upload the file, the maven zips the file into a .9kb file

**Comment by garronej** [comment]
Hello @archimod95,  

I don't know... what are you doing exactly?  

Have you considered using the GitHub Action of the Starter Template? 

https://github.com/keycloakify/keycloakify-starter?tab=readme-ov-file#github-actions  

When you bumpt the package.json version it creates a github release and publishes the JARs as artifacts:  

https://github.com/keycloakify/keycloakify-starter/releases/tag/v10.0.0  

You can then download the JAR at container init:  

```yaml
keycloak:
  initContainers: |
    - name: realm-ext-provider
      image: curlimages/curl
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          # Replace USER and PROJECT.    
          curl -L -f -S -o /extensions/keycloakify-starter.jar https://github.com/USER/PROJECT/releases/latest/download/keycloak-theme-for-kc-24.jar

      volumeMounts:
        - name: extensions
          mountPath: /extensions

  extraVolumeMounts: |
    - name: extensions
      mountPath: /opt/bitnami/keycloak/providers

  extraVolumes: |
    - name: extensions
      emptyDir: {}
```

https://docs.keycloakify.dev/importing-your-theme-in-keycloak
