### ISSUE TITLE
CLI option to skip rmSync resourcesDirPath

### ISSUE THREAD

**Issue by jackie-linz** [keycloakify/keycloakify#673]
We have custom keycloak image that's built with our own extensions, and have a docker-compose file for local development environment.

When developing with vanilla Keycloak theme, we could mount the custom themes folder into the running container like the following and any theme change could be reflected without restart.

```yaml
services:
  auth:
    image: "my-keycloak-image"
    command:
      # these parameters to have theme change show up without restarting container
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
    volumes:
      - ./my-themes:/opt/keycloak/themes
```

When using keycloakify, it builds a JAR file and immediately deletes the `resourcesDirPath`:

https://github.com/keycloakify/keycloakify/blob/main/src/bin/keycloakify/keycloakify.ts#L128

Please provide a CLI option to skip the `rmSync` call so we can mount the theme folder into the container similar to what we used to do
