### ISSUE TITLE
Documentation: Update curl for the helm template init container example

### ISSUE THREAD

**Issue by jdockeray** [keycloakify/keycloakify#740]
On this [page](https://docs.keycloakify.dev/importing-your-theme-in-keycloak), the second example for version 24.0.5 the curl command should use the mounted volume 

currently:
```
curl -L -f -S -o /extensions/keycloakify-starter.jar  ...
```

updated:
```
curl -L -f -S -o /emptydir/app-providers-dir/keycloakify-starter.jar ...
```

**Comment by garronej** [comment]
Hey @jdockeray,  

Thank you for reaching out, 
Are you sure though?  

It depends where you have you empty dir mounted. In the instruction we have:  

```yaml
keycloak:
  initContainers: |
    - name: realm-ext-provider
      image: curlimages/curl
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          # Replace USER and PROJECT.    
          curl -L -f -S -o /extensions/keycloakify-starter.jar https://github.com/USER/PROJECT/releases/latest/download/keycloak-theme-for-kc-24.jar

      volumeMounts:
        - name: extensions
          mountPath: /extensions

  extraVolumeMounts: |
    - name: extensions
      mountPath: /opt/bitnami/keycloak/providers

  extraVolumes: |
    - name: extensions
      emptyDir: {}
```

If you want your suggestion to work you would have to write:  

```yarn
keycloak:
  initContainers: |
    - name: realm-ext-provider
      image: curlimages/curl
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          # Replace USER and PROJECT.    
          curl -L -f -S -o /emptydir/app-providers-dir/keycloakify-starter.jar https://github.com/USER/PROJECT/releases/latest/download/keycloak-theme-for-kc-24.jar

      volumeMounts:
        - name: extensions
          mountPath: /emptydir/app-providers-dir

  extraVolumeMounts: |
    - name: extensions
      mountPath: /opt/bitnami/keycloak/providers

  extraVolumes: |
    - name: extensions
      emptyDir: {}
```

But it's apple to oranges isn't it?

**Comment by jdockeray** [comment]
Hey @jdockeray,

Thanks for replying and maintaining this great project!

I am pretty sure. There are two code samples on that page, the first one (which you shared) is fine because the mount path is extensions. But in the second sample, which looks like this: 

```yaml
keycloak:
  initContainers: |
    - name: keycloak-plugin
      image: curlimages/curl
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          # Replace USER and PROJECT.    
          curl -L -f -S -o /extensions/keycloakify-starter.jar https://github.com/USER/PROJECT/releases/latest/download/keycloak-theme-for-kc-24.jar

      volumeMounts:
        - name: empty-dir
          mountPath: /emptydir

  extraVolumeMounts:
    - mountPath: /opt/bitnami/keycloak/providers
      name: empty-dir
      subPath: app-providers-dir
    
  extraVolumes:
    - emptyDir: {}
      name: empty-dir
```
The mountPath for volume mounts is `/emptydir`, but the curl command still references `/extensions/`, so the downloaded jar would not get mounted in the volume.
