### ISSUE TITLE
sh: 1: storybook: not found

### ISSUE THREAD

**Issue by jucajuca** [keycloakify/keycloakify#800]
Hello,

After folllwing the quick start I keep getting this error:

sh: 1: storybook: not found

Any ideas what could be happening?
Is there a dockerfile to run the project?

**Comment by jucajuca** [comment]
Hello,

These are the results:

v20.9.0
10.1.0
1.22.22

Can you let me know which versions should I use?

**Comment by jucajuca** [comment]
Hello,

I am running this in Linux. I need to work with React.

Linux local_name 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

I can also run it within a docker container.

**Comment by jucajuca** [comment]
I created a dockerfile and a docker-compose file to run this project.

Feel free to add them to the code.

```
FROM node:20

# Install Git
# RUN apt-get update && apt-get install -y git

# Clone the repository
RUN git clone https://github.com/keycloakify/keycloakify-starter /app/keycloakify-starter

# Set the working directory
WORKDIR /app/keycloakify-starter

# Install dependencies
RUN yarn install # Feel free to use another package manager (if you do, remove the .yarn.lock)

# Add the story
# RUN npx keycloakify add-story # Select login.ftl (for example)

# Expose the port for Storybook (default is 6006)
EXPOSE 6006

# Set the command to run Storybook
CMD ["npm", "run", "storybook"]


```


```

version: '3.8'

services:
  keycloakify:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/keycloakify-starter/src
    ports:
      - "6006:6006"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "storybook"]






```
